spring:
  application:
    name: servicio-productos
# se movio al servidor de conmfiguración
#  datasource:#    url: jdbc:mysql://localhost:13306/spring_microservicios_cloud
#    username: mysql
#    password: secret
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:#    database-platform: org.hibernate.dialect.MySQL8Dialect #esta relacionado al servidor mysql#    hibernate:#      ddl-auto: create #crea las tablas con las noataciones jpa
#logging:#  level:#    org:
#      hibernate:
#        SQL: debug
server:
  port: ${PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
